shayonj/pg-osc

README.md, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb
This ensures that FKs on other tables that point to the primary table that is being
altered, continue pointing to the same table after rename swap. When swap happens, 
a.k.a rename. The FKs on other tables will point to the table renamed table (old one). 
Consider this: 
Primary table: `books`
Table with FK pointing to books: `chapters`
after swap we have three tables
- `books`
- `chapters`
- `pgosc_old_primary_table_books`
However, the FK on `chapters` (`book_id`) is now pointing to `pgosc_old_primary_table_books`, instead of `books`. 
This PR fixes that by dropping those FKs (in the same transaction as swap) then adds them back again on the new table, after the rename.
=> Ensure FKs from other tables are updated on swap

lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb
We were doing begin/commit but this now performs
a rollback on any exception raises. Similar to
PG::Connection#transaction. However, this is easier
to test
`async_exec` is an alias to `exec`, just being explicit
=> Support for transaction, rollbacks and moving to async_exec 

lib/pg_online_schema_change/orchestrate.rb
Since we are copying the data onto a fresh new table,
that looks (structurally) like the original table, its
better to run ANALYZE so planners are up to date.
We do it once after swap, just as good measure, also in case
the duration to replay change is long (true, when working with large
tables and copying a table can take hours, while changes are being accumulated
in the audit table)
cc @jfrost
https://github.com/shayonj/pg-online-schema-change/pull/6#issuecomment-1025198001
=> Run ANALYZE post COPY and ALTER statements

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/client_spec.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/support/database_helpers.rb, todo
We were taking in schema as the input
but majority of the code written just
assumed public. This now sets the
search_path to the schema before performing
any operations.
Tweaks to specs and spec helpers to respect
the new settings and setting the search_path
accordingly in testing environment too
=> Support to perform operations in any schema

lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/query.rb, spec/lib/query_spec.rb, todo
The design is centered around `client.table`, hence this validation check. Multiple invocations of pgosc is also possible if there is a need to run alter statements against different tables. pgosc supports multiple `ALTER` statements in a single invocation.
=> Ensure all alter statements belong to the same table

README.md, lib/pg_online_schema_change/cli.rb, lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/functions.rb, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/client_spec.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/support/database_helpers.rb
- Query.storage_parameters_for returns storage params (vaccum, fill_factor, etc)
to be reset post swap on the new table.
- This drops the old primary table. The setting
is controlled via -f/--drop flag. Default being false (won't drop)
- Audit table is dropped by default (since its empty)
- statement_timeout and client_min_messages are reset
- Updated fix_serial_sequence to use `pg_attrdef.adbin`
since `adsrc` is deprecated and removed in PG12 onwards.
Also this handles schemas nicely when search_path is set.
closes https://github.com/shayonj/pg-online-schema-change/issues/12
=> Restore storage parameters post swap & drop+cleanup

README.md, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb
This way we validate the FKs that were added
w/ NOT VALID during the swap. This is a safe operation
to run post swap (since it doesn't block on the lock).
Also leaves the `pg_get_constraintdef` in a good state.
In other words, post this step, the FK's won't have NOT VALID,
that were added during the swap
closes https://github.com/shayonj/pg-online-schema-change/issues/11
=> Validate constraints post swap

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/support/database_helpers.rb
First stress test was good. Came across some issues and
here are the fixes
- Escape rows being replayed. Rows can contain
quotes, emojis, etc. Using escape_string for this.
- Respect case sensitive columns. Using quote_indent
for this
- Replay all 1000 rows at once. Replaying 1 row at
a time, leads to a very slow migration.
- Ensure primary keys are quoted since they can
be string/uuid as well
- Ensure triggers and shadow tables are cleaned, 
in case process breaks mid way before alter, swap, etc
=> Fixes post first stress test

README.md, lib/pg_online_schema_change.rb, lib/pg_online_schema_change/cli.rb, lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/support/database_helpers.rb, todo
This introduces `wait_time_for_lock` and `kill_backends` as new flags.
By default `pgosc` won't kill any backends if it cannot acquire an
`AccessExclusiveLock` to perform the swap. It will retry upto 3 times
and for the duration specified in `wait_time_for_lock` (default: `10s`).
So, in total 30s. Configurable. If `kill_backends`/`kill-backend`
is set to true (supplied), then it will kill the backend on each try
it couldn't acquire the lock, upto 3 times before exiting. Though,
after killing the backends after 1st attempt should work.
Specs added. A bit messy for now. Refactor in the end
closes https://github.com/shayonj/pg-online-schema-change/issues/16
=> Introduce the ability to kill competing transactions that hold exclusive lock during swap

lib/pg_online_schema_change/orchestrate.rb, spec/lib/orchestrate_spec.rb, todo
To avoid any other/future strong locks (like during drop/cleanup, which should be simple operations, as it can happen during error handling, or post completion)
=> Drop trigger post swap and not cleanup

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb
This ensures that when the delta count is < 20 rows (which indicates its time for swap),
it will replay those rows *after* the access exclusive lock
is acquired and then proceed to performing the swap.
This finally ensures no data loss - since we have already
acquired an access exclusive lock and can replay the <20 replays
swiftly, while other backend wait for a brief while and continue on with the process.
Changed Query.run api to support the use of existing
transaction such that lock is held
fixes https://github.com/shayonj/pg-online-schema-change/issues/25
Ran a stress test with `pgbench` and successfully add a new column on a
table with 500M rows with no pending rows in the audit table and no data
loss. Confirmed by ensuring all rows from old primary table exist in new table. 
Will …
=> Replaying remaining <20 rows (below delta) before swap

lib/pg_online_schema_change/orchestrate.rb, spec/lib/orchestrate_spec.rb, todo
Since we have the ability to kill competing backends (opt-in via a flag),
and additionally setting up trigger requires lock - this change attempts
to first acquire a lock and if kill-backends is supplied then it will kill the
backends and retry again to setup the triggers. If no-kill-backends is provided
it will try upto 3 times and fail.
This also means we will attempt to try and acquire access exclusive lock twice -
once when setting up triggers and once during swap. Accordingly kill backends (if supplied).
Added specs and tested.
This change makes the project feature complete for v1 rollout. Whats pending are
some refactors/code organization, linter and a release process (https://github.com/shayonj/pg-online-schema-change/issues/13), and …
=> Acquire lock and attempt to kill backends when setting up trigger

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, lib/pg_online_schema_change/replay.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/lib/replay_spec.rb
This has few advantages
- Allows to perform custom copy statements, such as
backfil new rows (https://github.com/shayonj/pg-online-schema-change/issues/30)
- Reduce wasteful copies
- Use custom new triggers in future
Since alter statement now runs before copy,
this also now intelligently handles copying data for
columns that dropped or renamed. If its dropped, the data
is skipped. If its renamed, the data is accordingly mapped.
Abstracted the logic inside Query.copy_data_statement
cc/fyi @jfrost
=> Alter before copy

lib/pg_online_schema_change/orchestrate.rb, spec/lib/orchestrate_spec.rb
Since we are not restoring index/sequence name for now,
ensuring the table names are unique so that if we run the same
operation on the same table, there is no sequence conflict. The sequence
will get overriden on the table anyways, but won't fail and complain
when trying to create a shadow before the swap. This is temporary until
we support restoring original index and sequence names(https://github.com/shayonj/pg-online-schema-change/issues/20). Can be a pro feature too
=> Ensure table names are unique and preset

lib/pg_online_schema_change/cli.rb
This is to ensure the Struct build up doesn't fail
and also non required feels have defaults for better validations
=> Ensure there is a default value for copy_statement

lib/pg_online_schema_change/functions.rb, spec/lib/orchestrate_spec.rb
There is no need to rename/replace constraint name here, since
these are localized to the table (shadow table). Replacing logic
isn't fully tested and results in edge cases where replacing substring
that matches table name and shadow table name ends up with longer constraint
name if you run pg-osc multiple times on a table. This keeps it simple and consistent
at all times
=> Preserve constraint names on the shadow table

lib/pg_online_schema_change/orchestrate.rb, spec/lib/orchestrate_spec.rb
This is mostly proofing against any cases
where drop constraint goes into a lock queue
and the transaction sits idle/handing while have
acquired access exclusive lock on the primary table.
In such a case the transaction will rollback and program
will end (with cleanup).
=> Set statement_timeout for swap to 5s

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/replay.rb, spec/lib/orchestrate_spec.rb, spec/lib/replay_spec.rb, spec/support/database_helpers.rb
This ensures that all items added to audit table
will be read in the order they came, using the new primary key.
Using the old primary key has edge case if updates happened on the
same row and re-purposing the same primary key will lead to un-ordered
behavior
fixes https://github.com/shayonj/pg-osc/issues/48
=> Introduce primary key on audit table for ordered reads

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/replay.rb, spec/lib/orchestrate_spec.rb
This attaches the identifier on the column name
and that way we can ensure the column is not generic
enough so much so that it may conflict with column
names of primary table. 
Also updates the column name to be more easy to
read.
Similar to: https://github.com/shayonj/pg-osc/pull/50
=> Uniquely identify trigger_time column

spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/lib/replay_spec.rb, spec/support/database_helpers.rb
This refactors tests a bit to abstract
the common operation of running a querying
and asserting the outcome into a function.
This way the callers are bit clean, easy to work
with and more deterministic
=> Abstract assertions into a helper function

Gemfile.lock, lib/pg_online_schema_change/orchestrate.rb
This way it won't begin/commit any existing
transaction and re-use existing transaction
that will next copy data statements.
Caught this on 8k+ commits/s. Doesn't
slow down below it
=> Reuse existing transaction open for reading table columns

README.md, docs/load-test.md, lib/pg_online_schema_change.rb, lib/pg_online_schema_change/cli.rb, lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/replay.rb, spec/lib/client_spec.rb, spec/support/database_helpers.rb
On tables with high volume workloads,
having the ability to tune PULL_BATCH_COUNT
and DELTA_COUNT is nice for faster catchup and swap.
The default values are 1000 and 20 respectively. Which means,
in one pass pg-osc will replay 1000 rows and if the count is <20
then it will perform the swap and replay.
By introducing new cli flags (`--pull-batch-count`, `--delta-count`),
these figures can be tuned further
Fixes: https://github.com/shayonj/pg-osc/issues/21
=> Introduce configurable PULL_BATCH_COUNT and DELTA_COUNT

Gemfile.lock, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/replay.rb, spec/fixtures/bench.sql, spec/lib/orchestrate_spec.rb
This has few changes
- Once it replays items from the audit table, it deletes
those rows after. However, it was deleting rows by the PK
of the primary table and not the audit table, which created
a race condition on high volume tables.
- Moves up setting alter statement refresh commands in the Store
to avoid any risk of leaky transactions in the end
Tested this manually using pgbench and no longer seeing
any mis match between data post pg-osc run.
Will be bringing that integration test to CI (https://github.com/shayonj/pg-osc/issues/61), so we can run them
on every commit and catch regressions early
fixes: https://github.com/shayonj/pg-osc/issues/58
Nice find @jfrost !
=> Delete items by audit table PK when replaying

lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb
`setval` updates the `currval` on the sequence. So, we don't need to do a `+1` on the `max. Doing so, would skip a sequence value. Added a breaking spec. 
ht/ https://github.com/shayonj/pg-osc/pull/73#discussion_r979254672
=> off-by-one: Don't skip PK sequence value by one

docker-compose.yml, lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/helper.rb, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/client_spec.rb, spec/lib/query_spec.rb
Postgres has a notorious issue of requiring double quotes in relation identifiers when uppercase letters are contained. In other words, if a table was created with `CREATE TABLE "CamelCaseTable" blah`,  referring to the table using `CamelCaseTable` in queries will trigger a relation not found error. One has to use `"CamelCaseTable"`. It seems that upstream `pg_query` does not handle this as well.
Luckily Ruby is interpreted so I'll be able to modify locally to make the tool work for my use case (thanks!), but I thought a PR might be nice.
Putting it up as draft right now as I have not added test cases.
=> Supports tablenames containing uppercase letters

lib/pg_online_schema_change/orchestrate.rb, spec/lib/orchestrate_spec.rb
Also fix the table name for this part of the process.
This is a quick fix for tables with no storage parameters but does not fix the issue if autovacuum is enabled but other storage parameters are indeed set.
Fixes #82
=> Re-enable autovacuum

README.md, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/support/database_helpers.rb
pg-osc will now re-create any views after the table name swap. Because pg-osc uses shadow tables, after the name swap happens, views can continue to refer the old table name. This isn't ideal.
Instead, we now perform a `CREATE OR REPLACE VIEW`... after the swap is performed. We do it after swap to ensure any view creation doesn't keep the exclusive lock held for a longer duration.
Closes: https://github.com/shayonj/pg-osc/issues/81
=> Support for views

lib/pg_online_schema_change/functions.rb, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/lib/replay_spec.rb
Calling an `ALTER` with a transaction open during serializable while we copy data onto the audit table could potentially lead to lock queues. This avoids doing so by removing the `disable_vaccum` function and taking advantage of `WITH` directive when setting up the shadow and audit table in the first place. Thus avoiding the need to perform an `ALTER` on audit table or shadow table and avoid locking. 
After some good findings from https://github.com/shayonj/pg-osc/issues/94 
h/t @yash-toddleapp
=> Create shadow and audit with auatovacuum default

lib/pg_online_schema_change/cli.rb
Currently the `-v` and `--version` options don't actually show the version. Here's what you get:
```
% pg-online-schema-change --version
No value provided for required options '--alter-statement', '--dbname', '--host', '--username'
```
This PR maps the `-v` and `--version` options to the correct method:
```
% pg-online-schema-change --version
0.9.2
```
=> Adding support for showing the gem version with -v or --version.

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/support/database_helpers.rb
https://github.com/shayonj/pg-osc/issues/115
Use postgres `pg_get_serial_sequence` function to fetch the real sequence name.
Please see individual commits for the approach.
=> INSERT's are failing for long table names 115

lib/pg_online_schema_change/query.rb, spec/lib/query_spec.rb
The search_path can get lost or not set when looking for the view definition via `pg_get_viewdef`. Hence we now pass in the schema in addition to the view name for `Query.view_definitions_for`
fixes: https://github.com/shayonj/pg-osc/issues/112
=> Get view definition of a view from dedicated schema

lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, spec/lib/query_spec.rb
Just an optimization change to ensure a single transaction opened for too long when dealing with large tables
Related: https://github.com/shayonj/pg-osc/issues/119
=> Validate one constraint at a time

README.md, lib/pg_online_schema_change/cli.rb, lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/orchestrate.rb, spec/lib/orchestrate_spec.rb, spec/support/database_helpers.rb
In case users would like to run the validate constraint post swap manually or keep the constraints in a NO VALID state for older rows, there is now an option to do that with --skip-foreign-key-validation.
Another unrelated bugfix with Error reference class
Related: https://github.com/shayonj/pg-osc/issues/119
=> Introduce --skip-foreign-key-validation

README.md
i think this is where this should link to?
=> fix and add links to caveats section

lib/pg_online_schema_change/query.rb, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/lib/replay_spec.rb, spec/support/database_helpers.rb
Right now it was doing so only for the schema client was instantiated with. Now it handles views in any schema that may reference the table in action
Fixes: https://github.com/shayonj/pg-osc/issues/129
=> Refresh views across all schemas post swap

.github/workflows/ci.yaml, .github/workflows/smoke-tests-13-6.yaml, .github/workflows/smoke-tests-9-6.yaml, lib/pg_online_schema_change/client.rb, lib/pg_online_schema_change/orchestrate.rb, lib/pg_online_schema_change/query.rb, pg_online_schema_change.gemspec, spec/lib/orchestrate_spec.rb, spec/lib/query_spec.rb, spec/lib/smoke_spec.rb
Introducing a new `log_progress` function to estimate progress during data operations. This function compares the sizes of the parent table and the shadow table using `pg_table_size`. As we can't count the rows directly due to the ongoing transaction, `pg_table_size` provides the closest estimate. Prior to this, we perform a vacuum and analyze on the parent table to enhance the accuracy of the size measurement.
It's important to note that the `pg_table_size` of the shadow table may not exactly match the parent table, especially for larger tables. This discrepancy is expected, since the logging is a best effort measure. The function will terminate once `copy_data` completes as it watches for an instance var - `@copy_finished`
Progress is logged at 60-second intervals.
Lastly, this change …
=> Introduce the ability to show estimate progress of copy

.gitignore, Gemfile.lock, lib/pg_online_schema_change/cli.rb, lib/pg_online_schema_change/client.rb, spec/lib/client_spec.rb
Validate the value of `delta_count` to be smaller than the `pull_batch_count` value to avoid situations where the replay ends after one cycle and the table is swapped too soon without the full replay completing.
=> Validate delta_count value against pull_batch_count
